from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class FortuneRequest(BaseModel):
    """Backward-compatible one-step request.

    Kept for old frontend/tests. New UI should prefer:
    1) FortuneDrawRequest -> /api/fortune/draw
    2) FortuneInterpretRequest -> /api/fortune/interpret
    """

    question: str = Field(..., min_length=1)
    aspect: str | None = "auto"
    sign_id: str | None = None
    style: str | None = "modern"


class FortuneDrawRequest(BaseModel):
    """Stage 1: draw only.

    This endpoint must not call LLM or Chroma retrieval. It only picks one sign
    and returns a lightweight sign card for the ritual page.
    """

    question: str | None = None
    aspect: str | None = "auto"
    sign_id: str | None = None


class FortuneDrawResponse(BaseModel):
    draw_id: str
    sign_id: str
    sign_key: str
    level: str | None = None
    level_class: str | None = None
    title: str | None = None
    story_title: str | None = None
    keywords: list[str] = Field(default_factory=list)
    aspect: str | None = "auto"
    question: str | None = None
    source: str = "backend_draw"
    resolved_aspect: str | None = None
    aspect_prediction: dict[str, Any] | None = None


class FortuneInterpretRequest(BaseModel):
    """Stage 2: interpret selected sign.

    sign_id is required here because the user has already drawn a sign card.
    """

    question: str = Field(..., min_length=1)
    aspect: str | None = "auto"
    sign_id: str = Field(..., min_length=1)
    style: str | None = "modern"
    draw_id: str | None = None


class FortuneResponse(BaseModel):
    sign_id: str
    sign_key: str
    aspect: str
    resolved_aspect: str | None = None
    aspect_prediction: dict[str, Any] | None = None
    answer: str

    # Structured AI report generated by Qwen.
    ai_report: dict[str, Any] | None = None

    # Lightweight question understanding result.
    question_analysis: dict[str, Any] | None = None

    citations: list[dict[str, Any]]
    evidence: list[dict[str, Any]]

    # Convenience fields for frontend display.
    level: str | None = None
    title: str | None = None
    story_title: str | None = None

    # Five-dimension fortune radar analysis.
    radar_analysis: dict[str, Any] | None = None

    # Semantically similar signs recommended by Chroma embedding retrieval.
    similar_signs: list[dict[str, Any]] = Field(default_factory=list)

    # draw_id connects report with the stage-1 draw event.
    draw_id: str | None = None

    # Reserved for retrieval/evaluation metrics.
    metrics: dict[str, Any] = Field(default_factory=dict)
